accounts/urls.py
from django.urls import path
from accounts import views as accounts_views

app_name = 'local_accounts'

urlpatterns = [
    path('login/', accounts_views.CustomLoginView.as_view(), name='login'),
]

config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _
from django.db import models


class Account(AbstractUser):
    phone_number_validator = RegexValidator(
        '^\d{2,3}-\d{3,4}-\d{4}$',
        _('-와 12자 이하의 숫자만 사용합니다'),
        _('invalid phone_number')
    )
    phone_number = models.CharField(
        _('휴대폰 번호'),
        validators=[phone_number_validator],
        max_length=15,
        unique=True,
        null=True
    )

    GENDER_MALE = 0
    GENDER_FEMALE = 1
    GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE, 'Female')]

    name = models.CharField(_('이름'), max_length=10, validators=[UnicodeUsernameValidator], null=True)
    gender = models.IntegerField(_('성별'), choices=GENDER_CHOICES, null=True)
    birth_data = models.DateField(_('생년월일'), null=True)

    # 도로명 주소
    si_do = models.CharField(_('시도명'), max_length=30, null=True)
    si_gun_goo = models.CharField(_('시군구명'), max_length=30, null=True)
    eup_myun_dong = models.CharField(_('읍면동명'), max_length=30, null=True)
    lee = models.CharField(_('법정리명'), max_length=30, null=True)

    road_name = models.CharField(_('도로명'), max_length=100, null=True)
    building_id = models.CharField(_('건물번호'), max_length=30, null=True)

    detail_address = models.CharField(_('상세주소'), max_length=200, null=True)

    class Meta:
        verbose_name = _('사용자')
        verbose_name_plural = _('사용자')

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.utils.translation import gettext_lazy as _


class LoginForm(AuthenticationForm):
    username = UsernameField(label=_('아이디'), widget=forms.TextInput(attrs={'autofocus': True}))

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
    }

accounts/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import render

# Create your views here.
from accounts.forms import LoginForm


class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'
    form_class = LoginForm

config/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/accounts/login.css' %}" />
{% endblock %}

{% block content %}
    {% load widget_tweaks %}
    {% load socialaccount %}
    {% providers_media_js %}

    <h1><a href="{% url 'index' %}">Django example</a></h1>
    <h2>로그인</h2>

    <form id="login-form" method="post">
        {% csrf_token %}

        {{ form.non_field_errors }}

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
    {% endfor %}

    {% for field in form.visible_fields %}
        <div class="form-field">
            <label for="{{ field.name }}">{{ field.label }}</label> <br/>
            {{ field.errors }}
            {{ field|add_class:"form-control" }}
            {{ field.help_text }}
        </div>
    {% endfor %}

        <br/>
        <button type="submit" class="form-control">
            로그인
        </button>

    {% if user.is_authenticated %}
        <a href="{% url 'account_logout' %}">로그아웃</a> <br/>
        {{ user.username }}님이 로그인 중
    {% else %}
        <a href="{% provider_login_url 'kakao' %}" class="form-control kakao-login">
            <button>카카오 로그인</button>
        </a>
        <a href="{% provider_login_url 'naver' %}" class="form-control naver-login">
            <button>네이버 로그인</button>
        </a>

        <a href="/accounts/signup" class="mr-2">회원가입</a>
        <a href="/accounts/signup">비밀번호 찾기</a> <br/>
    {% endif %}
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block css %}{% endblock %}

    <title>Django example</title>
</head>
<body>
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% block script %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <header>
        <nav class="navbar navbar-expand-sm bg-light">
            <h1 class="navbar-brand">Django example</h1>
            <!-- Links -->
            <ul class="navbar-nav ml-auto">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'local_accounts:login' %}">로그인</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">회원가입</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">마이페이지</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
{% endblock %}